version: "3"
services:
  next_web:
    container_name: next_web
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "80"
    environment:
      VIRTUAL_HOST: "next.app.local.ro"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "next.app.local.ro"
      LETSENCRYPT_EMAIL: "cosmin.cotublea@roweb.ro"
    networks:
      - nginx-proxy
      - next

  next_app:
    container_name: next_app
    command: /bin/sh /var/www/docker/entrypoint.sh
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/node_modules
      - ./ssl:/etc/certs
    ports:
      - "8080:8080"
    networks:
      - next

networks:
  next:
  nginx-proxy:
    external: true
