version: '3'
services:
  next-start-nginx:
    container_name: next-start-nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
      args:
        VHOST_FILE: ${VHOST_FILE}
    volumes:
      - ./:/var/www
    ports:
      - 80
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOSTS}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${VIRTUAL_HOSTS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - next-start
      - nginx-proxy

  next-start-redis:
    container_name: next-start-redis
    build:
      context: ./
      dockerfile: docker/redis/Dockerfile
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=511
    networks:
      - next-start

  next-start-node:
    container_name: next-start-node
    command: /bin/sh ${ENTRYPOINT}
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    depends_on:
      - next-start-redis
    volumes:
      - ./:/var/www
      - ./node_modules:/var/www/node_modules
      - ../nginx-proxy/certs:/etc/certs
    restart: unless-stopped
    networks:
      - next-start

networks:
  next-start:
  nginx-proxy:
    external: true
