version: "3"
services:
  next_web:
    container_name: next_web
    build:
      context: ./
      dockerfile: docker/web.docker
    volumes:
      - ./:/app
    ports:
      - "80"
    environment:
      - "VIRTUAL_HOST=next.app.local.ro"
      - "VIRTUAL_PROTO=http"
      - "VIRTUAL_PORT=80"
    networks:
      - nginx-proxy
      - next

  next_app:
    container_name: next_app
    command: /bin/sh /app/docker/entrypoint.sh
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - ./ssl:/etc/certs
    ports:
      - "8080:8080"
    networks:
      - next

networks:
  next:
  nginx-proxy:
    external: true
